### ISSUE TITLE
tdagent package provider fails under puppet 6.5.0

### ISSUE THREAD

**Issue by mwhahaha** [soylent/konstantin-fluentd#39]
The current version of the tdagent provider is throwing an error when being invoked under 6.5.0.  It's likely because it's being handled inside a parser function definition rather than being loaded correctly.

```
     Puppet::PreformattedError:
       Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/package: Could not autoload puppet/provider/package/tdagent: Could not autoload puppet/provider/package/gem: superclass must be a Class (Module given) (file: /home/user/Documents/workspace/openstack/puppet-tripleo/spec/fixtures/modules/certmonger/manifests/init.pp, line: 4, column: 3) on node user.localdomain
     Shared Example Group: "tripleo::certmonger::ca::local" called from ./spec/classes/tripleo_certmonger_ca_local_spec.rb:56
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/provider/package_targetable.rb:23:in `<top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/provider/package/gem.rb:1:in `require'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/provider/package/gem.rb:1:in `<top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load_file'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:201:in `load'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/type.rb:1808:in `provider'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/type.rb:1859:in `provide'
     # ./spec/fixtures/modules/fluentd/lib/puppet/provider/package/tdagent.rb:3:in `<module:Functions>'
     # ./spec/fixtures/modules/fluentd/lib/puppet/provider/package/tdagent.rb:2:in `<top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load_file'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:81:in `block in loadall'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:79:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:79:in `loadall'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:215:in `loadall'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/metatype/manager.rb:127:in `newtype'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/type/package.rb:10:in `<module:Puppet>'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/type/package.rb:9:in `<top (required)>'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:66:in `load_file'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/autoload.rb:201:in `load'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/metatype/manager.rb:172:in `type'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_resource_support.rb:105:in `find_builtin_resource_type'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_resource_support.rb:70:in `find_resource_type'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_resource_support.rb:23:in `create_resources'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_support.rb:340:in `create_resources'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:865:in `block in eval_ResourceExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:862:in `map'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:862:in `eval_ResourceExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:92:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:358:in `eval_BinaryExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:487:in `eval_RelationshipExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:92:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `block in eval_BlockExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `reduce'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `eval_BlockExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:90:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/parser/evaluating_parser.rb:63:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:32:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:72:in `block (2 levels) in evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:71:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:71:in `block in evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:70:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:70:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast.rb:30:in `safeevaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/resource/type.rb:136:in `evaluate_code'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/resource.rb:78:in `block in evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/resource.rb:70:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:385:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:385:in `evaluate_classes'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/functions/include.rb:48:in `include'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/dispatch.rb:60:in `invoke'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/dispatcher.rb:43:in `block in dispatch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/dispatcher.rb:42:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/dispatcher.rb:42:in `dispatch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/function.rb:46:in `block in call'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/function.rb:45:in `catch'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/functions/function.rb:45:in `call'
     # :1:in `block in call_function'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_support.rb:305:in `eval'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_support.rb:305:in `block in call_function'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/runtime3_support.rb:303:in `call_function'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:976:in `call_function_with_block'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:945:in `eval_CallNamedFunctionExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:92:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `block in eval_BlockExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `reduce'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:660:in `eval_BlockExpression'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:92:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # :in `stack'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/puppet_stack.rb:33:in `eval'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/puppet_stack.rb:33:in `stack'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:737:in `eval_Program'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:48:in `block in visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `each'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:42:in `visit_this'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/visitor.rb:92:in `visit_this_1'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/pops/parser/evaluating_parser.rb:63:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast/pops_bridge.rb:125:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/ast.rb:30:in `safeevaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/resource/type.rb:136:in `evaluate_code'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/resource.rb:78:in `block in evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/resource.rb:70:in `evaluate'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:592:in `evaluate_main'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:165:in `block (2 levels) in compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:165:in `block in compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/context.rb:65:in `override'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet.rb:266:in `override'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:154:in `compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/parser/compiler.rb:34:in `compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/catalog/compiler.rb:303:in `block (2 levels) in compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler/around_profiler.rb:58:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util/profiler.rb:51:in `profile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/catalog/compiler.rb:301:in `block in compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util.rb:231:in `block in benchmark'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/util.rb:230:in `benchmark'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/catalog/compiler.rb:299:in `compile'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/catalog/compiler.rb:54:in `block in find'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/node/environment.rb:433:in `with_text_domain'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/catalog/compiler.rb:53:in `find'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/indirector/indirection.rb:194:in `find'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:218:in `block in build_catalog_without_cache'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/context.rb:65:in `override'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet.rb:266:in `override'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:216:in `build_catalog_without_cache'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:231:in `block in build_catalog'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/cache.rb:17:in `get'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:230:in `build_catalog'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:28:in `load_catalogue'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/example/class_example_group.rb:7:in `catalogue'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/support.rb:8:in `block in subject'
     # /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/rspec-puppet-2.3.2/lib/rspec-puppet/matchers/create_generic.rb:82:in `matches?'
     # ./spec/classes/tripleo_certmonger_ca_local_spec.rb:36:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # TypeError:
     #   superclass must be a Class (Module given)
     #   /home/user/.rvm/gems/ruby-2.6.3@openstack/gems/puppet-6.5.0/lib/puppet/provider/package_targetable.rb:23:in `<top (required)>'
```

**Comment by dashcheulov** [comment]
Hi,
it's fixed on puppet agent side https://tickets.puppetlabs.com/browse/PUP-9794
Only with 6.5.0 I got ```Error: Could not autoload puppet/provider/package/gem: superclass must be a Class (Module given)
Error: Could not autoload puppet/provider/package/tdagent: Could not autoload puppet/provider/package/gem: superclass must be a Class (Module given)```
After updating `Notice: /Stage[main]/Puppet_agent::Install/Package[puppet-agent]/ensure: ensure changed '6.5.0-1bionic' to '6.6.0-1bionic'` the error has dissapeared.
